services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data: